#!/usr/bin/env python3
"""
Write the statistics strip into index.html, between its fences.

WHY THE NUMBERS ARE BAKED IN AND NOT FETCHED IN THE BROWSER. This site's support
page states it makes no third-party requests. Calling api.github.com from the
page would put every visitor's IP address on GitHub's servers and make that
claim false. Fetching at build time keeps the promise; the cost is that the
numbers are only true on the day they were written, which is what the weekly
workflow is for.

WHY THIS LIVES HERE AND NOT IN THE QuickImageViewer REPO. That repo already has
a stats workflow, but a workflow can only push to its own repository without a
personal access token stored as a secret. A second small script with no
credentials beats a cross-repo token.

Some figures are LIVE and some are FIXED, and they are labelled honestly in the
markup rather than blurred together: downloads, stars and releases move on their
own; formats, shortcuts and lines of code change only when the application does.

Usage:  python tools/build-stats.py [--check]
"""

import argparse
import io
import json
import os
import re
import sys
import urllib.request

REPO = 'icyhoty2k/QuickImageViewer'
API = 'https://api.github.com/repos/' + REPO
INDEX = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                     'index.html')

START = '<!-- STATS-START -->'
END = '<!-- STATS-END -->'

# Figures that change only when the application does. Kept here rather than
# fetched, because nothing on the internet knows them.
FIXED = [
    ('49',  'image formats', 'https://icyhoty2k.github.io/QuickImageViewer/#format-support'),
    ('224', 'keyboard shortcuts', 'https://icyhoty2k.github.io/QuickImageViewer/shortcuts.html'),
    ('60k', 'lines of C++', 'https://github.com/icyhoty2k/QuickImageViewer'),
]


def fetch(url):
    headers = {'Accept': 'application/vnd.github+json', 'User-Agent': 'icyhoty2k-site'}
    # Unauthenticated the API allows 60 requests an hour per IP, which is plenty
    # for one person locally. On a CI runner that IP is shared, so the token
    # matters there -- but its absence is not an error.
    token = os.environ.get('GITHUB_TOKEN') or os.environ.get('GH_TOKEN')
    if token:
        headers['Authorization'] = 'Bearer ' + token
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def gather():
    repo = fetch(API)
    releases = fetch(API + '/releases?per_page=100')
    downloads = 0
    for rel in releases:
        for asset in rel.get('assets') or []:
            downloads += asset.get('download_count') or 0
    return {
        'downloads': downloads,
        'stars': repo.get('stargazers_count') or 0,
        'releases': len(releases),
    }


def humanise(n):
    """1234 -> 1,234. Thousands separators, because 406 and 4060 should not
    look the same at a glance."""
    return '{:,}'.format(n)


def render(live):
    rows = [
        (humanise(live['downloads']), 'downloads',
         'https://github.com/icyhoty2k/QuickImageViewer/releases'),
        (humanise(live['stars']), 'stars',
         'https://github.com/icyhoty2k/QuickImageViewer/stargazers'),
        (humanise(live['releases']), 'releases',
         'https://github.com/icyhoty2k/QuickImageViewer/releases'),
    ] + FIXED

    out = [START,
           '<!-- Generated by tools/build-stats.py. Do not edit between the fences. -->',
           '<div class="statstrip">']
    for value, label, href in rows:
        out.append('    <a class="stat" href="%s">' % href)
        out.append('        <span class="stat-value">%s</span>' % value)
        out.append('        <span class="stat-label">%s</span>' % label)
        out.append('    </a>')
    out.append('</div>')
    out.append(END)
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    text = io.open(INDEX, encoding='utf-8').read()
    if START not in text or END not in text:
        sys.exit('ERROR: fences %s / %s not found in index.html' % (START, END))

    try:
        live = gather()
    except Exception as e:
        # Offline or rate-limited is not a failure. Leaving yesterday's numbers
        # in place is strictly better than blanking the strip.
        print('could not reach the API (%s) - leaving the strip alone' % type(e).__name__)
        return

    block = render(live)
    current = text[text.index(START):text.index(END) + len(END)]

    if current == block:
        print('current - %d downloads, %d stars, %d releases'
              % (live['downloads'], live['stars'], live['releases']))
        return

    if args.check:
        print('STALE - would write %d downloads, %d stars, %d releases'
              % (live['downloads'], live['stars'], live['releases']))
        sys.exit(1)

    io.open(INDEX, 'w', encoding='utf-8', newline='\n').write(text.replace(current, block))
    print('wrote - %d downloads, %d stars, %d releases'
          % (live['downloads'], live['stars'], live['releases']))


if __name__ == '__main__':
    main()
